package com.example.relaychat.core.model

enum class ProviderPreset(
    val id: String,
    val title: String,
    val detail: String,
    val profile: ProviderProfile,
    val defaultControls: RequestControls = RequestControls.Standard,
) {
    INTELALLOC_CODEX(
        id = "intelallocCodex",
        title = "intelalloc Codex",
        detail = "Preset for intelalloc's Codex-style Responses endpoint.",
        profile = ProviderProfile(
            presetId = "intelallocCodex",
            displayName = "intelalloc",
            apiStyle = ProviderApiStyle.RESPONSES,
            baseUrl = "https://backend.intelalloc.com",
            path = "/responses",
            model = "gpt-5.5",
            instructionsPrompt = "You are a practical coding and problem-solving assistant. Be precise, keep answers actionable, and surface uncertainty briefly when needed.",
            supportsImageInput = true,
            supportsWebSearch = true,
            supportsStreaming = true,
            supportsVerbosity = true,
            supportsStructuredOutputs = true,
            extraHeaders = "",
            extraBodyJson = """{"reasoning":{"summary":"detailed"}}""",
            reasoningMapping = ReasoningFieldMapping(path = ""),
            verbosityMapping = VerbosityFieldMapping(path = ""),
            webSearchMapping = ToggleFieldMapping(
                path = "tools",
                enabledJson = """[{"type":"web_search","external_web_access":true}]""",
                disabledJson = "[]",
            ),
        ),
        defaultControls = RequestControls(
            reasoningEffort = ReasoningEffort.XHIGH,
            verbosity = VerbosityLevel.HIGH,
            webSearchEnabled = false,
            toolChoice = ToolChoiceMode.AUTO,
            responseStorageEnabled = false,
            temperatureEnabled = false,
            temperature = 0.2,
            topPEnabled = false,
            topP = 1.0,
            maxOutputTokensEnabled = false,
            maxOutputTokens = 32768,
            seedEnabled = false,
            seed = 42,
            responseFormat = ResponseFormatOptions(),
        ),
    ),
    OPENAI_RESPONSES(
        id = "openAIResponses",
        title = "OpenAI Responses",
        detail = "Best fit for reasoning, verbosity, web search, response storage, and structured outputs.",
        profile = ProviderProfile(
            presetId = "openAIResponses",
            displayName = "OpenAI",
            apiStyle = ProviderApiStyle.RESPONSES,
            baseUrl = "https://api.openai.com/v1",
            path = "/responses",
            model = "gpt-5.4-mini",
            instructionsPrompt = "You are a practical assistant. Be precise, verify assumptions, and explain uncertainty briefly when needed.",
            supportsImageInput = true,
            supportsWebSearch = true,
            supportsStreaming = true,
            supportsVerbosity = true,
            supportsStructuredOutputs = true,
            extraHeaders = "",
            extraBodyJson = "",
            reasoningMapping = ReasoningFieldMapping(path = ""),
            verbosityMapping = VerbosityFieldMapping(path = ""),
            webSearchMapping = ToggleFieldMapping(path = ""),
        ),
        defaultControls = RequestControls(
            reasoningEffort = ReasoningEffort.MEDIUM,
            verbosity = VerbosityLevel.MEDIUM,
            webSearchEnabled = false,
            toolChoice = ToolChoiceMode.AUTO,
            responseStorageEnabled = true,
            responseFormat = ResponseFormatOptions(),
        ),
    ),
    OPENAI_CHAT_COMPLETIONS(
        id = "openAIChatCompletions",
        title = "OpenAI Chat",
        detail = "Fallback for providers that only expose the older chat endpoint.",
        profile = ProviderProfile(
            presetId = "openAIChatCompletions",
            displayName = "OpenAI Compatible",
            apiStyle = ProviderApiStyle.CHAT_COMPLETIONS,
            baseUrl = "https://api.openai.com/v1",
            path = "/chat/completions",
            model = "gpt-4.1-mini",
            instructionsPrompt = "You are a practical assistant.",
            supportsImageInput = true,
            supportsWebSearch = false,
            supportsStreaming = true,
            supportsVerbosity = false,
            supportsStructuredOutputs = true,
            webSearchMapping = ToggleFieldMapping(path = "", enabledJson = "true", disabledJson = "false"),
        ),
    ),
    OPENAI_IMAGE(
        id = "openAIImage",
        title = "Image / gpt-image-2",
        detail = "Dedicated intelalloc image endpoint preset for PNG generation.",
        profile = ProviderProfile(
            presetId = "openAIImage",
            displayName = "intelalloc Image",
            apiStyle = ProviderApiStyle.IMAGE_GENERATIONS,
            baseUrl = "https://backend.intelalloc.com/v1",
            path = "/images/generations",
            model = "gpt-image-2",
            instructionsPrompt = "",
            supportsImageInput = false,
            supportsWebSearch = false,
            supportsStreaming = false,
            supportsVerbosity = false,
            supportsStructuredOutputs = false,
            webSearchMapping = ToggleFieldMapping(path = "", enabledJson = "[]", disabledJson = "[]"),
        ),
        defaultControls = RequestControls(
            reasoningEffort = ReasoningEffort.NONE,
            verbosity = VerbosityLevel.MEDIUM,
            webSearchEnabled = false,
            toolChoice = ToolChoiceMode.AUTO,
            responseStorageEnabled = false,
            temperatureEnabled = false,
            topPEnabled = false,
            maxOutputTokensEnabled = false,
            seedEnabled = false,
            responseFormat = ResponseFormatOptions(),
        ),
    ),
    OPENROUTER_COMPATIBLE(
        id = "openRouterCompatible",
        title = "OpenRouter Compatible",
        detail = "A practical preset for OpenAI-style third-party routing endpoints.",
        profile = ProviderProfile(
            presetId = "openRouterCompatible",
            displayName = "OpenRouter Compatible",
            apiStyle = ProviderApiStyle.CHAT_COMPLETIONS,
            baseUrl = "https://openrouter.ai/api/v1",
            path = "/chat/completions",
            model = "openai/gpt-4.1-mini",
            instructionsPrompt = "You are a practical assistant.",
            supportsImageInput = true,
            supportsWebSearch = false,
            supportsStreaming = true,
            supportsVerbosity = false,
            supportsStructuredOutputs = true,
            webSearchMapping = ToggleFieldMapping(path = "", enabledJson = "true", disabledJson = "false"),
        ),
    ),
    LM_STUDIO_COMPATIBLE(
        id = "lmStudioCompatible",
        title = "LM Studio Local",
        detail = "Use a local OpenAI-compatible server on the same network.",
        profile = ProviderProfile(
            presetId = "lmStudioCompatible",
            displayName = "LM Studio Local",
            apiStyle = ProviderApiStyle.CHAT_COMPLETIONS,
            baseUrl = "http://127.0.0.1:1234/v1",
            path = "/chat/completions",
            model = "local-model",
            instructionsPrompt = "You are a practical assistant.",
            supportsImageInput = true,
            supportsWebSearch = false,
            supportsStreaming = true,
            supportsVerbosity = false,
            supportsStructuredOutputs = false,
            webSearchMapping = ToggleFieldMapping(path = "", enabledJson = "true", disabledJson = "false"),
        ),
    ),
    CUSTOM(
        id = "custom",
        title = "Custom",
        detail = "Start from your own endpoint and adjust everything manually.",
        profile = ProviderProfile(),
    ),
    ;

    companion object {
        fun fromId(id: String): ProviderPreset = entries.firstOrNull { it.id == id } ?: CUSTOM
    }
}
